[workspace]
members = [
"apps/rust/productivity_tool/occurrency_tracker" ]

[workspace.dependencies]
env_loader = {path = "libs/rust/env_loader"}
kafka_driver = {path = "libs/rust/kafka_driver"}
alert_entity = {path = "libs/rust/alert_entity"}
