# syntax=docker/dockerfile:1

# Base stage for cloning the repo
FROM rust:latest as code
WORKDIR /monorepo
RUN apt-get update -y && \
    apt-get install -y git && \
    git clone https://github.com/avilikof/monorepo .

# Builder stage
FROM rust:latest as builder
WORKDIR /monorepo

# Copy the entire repository from the previous stage
COPY --from=code /monorepo .

# Install necessary packages
RUN apt-get update -y && \
    apt-get install -y libsasl2-dev openssl musl-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Uncomment if you need to target musl for a fully static binary
# RUN rustup target add x86_64-unknown-linux-musl

# Build the Rust application
RUN cargo build --release -p alert_generator

# Final stage
FROM debian:bookworm-slim as template-rust
WORKDIR /app

# Install runtime dependencies
RUN apt-get update -y && \
    apt-get install -y libsasl2-dev openssl ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the built binary and any other necessary files from the builder stage
COPY --from=builder /monorepo/target/release/alert_generator /app/
COPY --from=builder /monorepo/.env /app/

# Set environment variables and run the service
ENV RUST_LOG=info
CMD ["./alert_generator"]
