[package]
name = "occurrency_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_loader = { path = "../../../../libs/rust/env_loader" }
kafka_driver = { path = "../../../../libs/rust/kafka_driver"}
log = "0.4.20"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }